### ISSUE TITLE
Feature Request: Ability to specify operations url and branch via config

### ISSUE THREAD

**Issue by emmetog** [P5vc/FetchApply#5]
While testing I'll likely be making many small changes to a branch of the operations repository and ideally applying them to a single or subset of servers for testing, before merging the PR to the master branch of the operations repository at which point it will be automatically pulled in and applied to all servers.

What do you think about defining the git url to the operations repository, and the branch that should be used, in the config file `/etc/fetchapply` directly? That would enable quick changes to the repository and branch, enabling easy testing while developing modules.

Btw, sorry for the barrage of new questions/issues here but I really like the concept of fetch apply and I'd love to be able to use it as a simple replacement (bash!) for more complex "traditional" provisioning tools like chef, puppet, ansible et al.

**Comment by P5vc** [comment]
I will look into this, thank you.

> Btw, sorry for the barrage of new questions/issues here

No worries! We appreciate your engagement and interest in Fetch Apply! All of your criticisms/suggestions have been constructive, and only help to improve Fetch Apply for everyone!

> I really like the concept of fetch apply and I'd love to be able to use it as a simple replacement (bash!) for more complex "traditional" provisioning tools like chef, puppet, ansible et al.

Thank you! We love to hear it! If you know anyone else who may be interested in Fetch Apply, please, spread the word! We're always looking to grow our community! :)

**Comment by P5vc** [comment]
We've added the ability to specify the git branch from within the configuration file. As for the `operations` repository URL, we're going to hold off on adding that option for now, as it could lead to too much inefficiency whenever Fetch Apply is run. Besides, we don't see a majority of our users changing their entire `operations` repository that frequently, and if they do, then they're better-off using the installation script to do it (so that the initializers are properly cleared, corresponding configuration changes are made, etc.).

I'm going to go ahead and close this issue, however feel free to add any more comments or re-open it if you notice any errors or would like to make a counter argument. Thanks!
